# License {-}
The online versions of these guides are freely available and licensed under the Creative Commons Attribution-NonCommercial-NoDerivatives (CC BY-NC-ND) license. This means that you are free to share them as they are, without making any modifications or using them for commercial purposes.

A minimal code that builds each guide is available via the link presented on [GitHub Repos](https://microbiome.complexdatainsights.com/appendices.html#imap-repos). If you are interested in obtaining a more detailed copy, you can purchase chapter-specific guides from the [CDI Online Store](https://complexdatainsights.com/shop).

By providing the guide repositories under a Creative Commons license, we continue to encourage the dissemination of knowledge and the accessibility of valuable resources for the benefit of the scientific community and beyond. We hope that this series inspires further exploration and advancements in the field of microbiome data analysis.

> Please note that the specific licensing terms and conditions may be found in the detailed license agreement provided with the guides.


# (PART) SAMPLE METADATA {-}
